name: Compiler

on:
  push:
    branches: [ main ]
    paths:
        'compiler/**'
  pull_request:
    branches: [ main ]
    paths:
        'compiler/**'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd compiler && cargo build --verbose
    - name: Run tests
      run: cd compiler && cargo test --verbose
