name: Interpreter

on:
  push:
    branches: [ main ]
    paths:
        'interpreter/**'
  pull_request:
    branches: [ main ]
    paths:
        'interpreter/**'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd interpreter && cargo build --verbose
    - name: Run tests
      run: cd interpreter && cargo test --verbose
